[firebase]
# Optional Web SDK values (client-side)
api_key = ""
auth_domain = ""
project_id = ""
messaging_sender_id = ""
app_id = ""
# Admin SDK Storage bucket
storage_bucket = ""

# Firebase Service Account (Admin SDK)
firebase_type = "service_account"
firebase_private_key_id = ""
firebase_private_key = """-----BEGIN PRIVATE KEY-----

-----END PRIVATE KEY-----"""
firebase_client_email = ""
firebase_client_id = ""
firebase_auth_uri = "https://accounts.google.com/o/oauth2/auth"
firebase_token_uri = "https://oauth2.googleapis.com/token"
firebase_auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
firebase_client_x509_cert_url = ""
firebase_universe_domain = "googleapis.com"

# Google AI Configuration
[google_ai]
api_key = ""

# Google Document AI Configuration
[google_documentai]
# Service Account Credentials (for Document AI API)
type = "service_account"
project_id = ""
private_key_id = ""
private_key = """-----BEGIN PRIVATE KEY-----

-----END PRIVATE KEY-----"""
client_email = ""
client_id = ""
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = ""
universe_domain = "googleapis.com"

# Document AI Processor Configuration
processor_id = ""
location = "us"

# Alternative: Use service account file path (uncomment if preferred)
# GOOGLE_APPLICATION_CREDENTIALS = "C:\\path\\to\\service-account.json"

# Admin Configuration (optional)
[admin]
admin_codes = ["DEFAULT_ADMIN_2025"]

# OCR Configuration (optional)
[ocr]
tesseract_path = "/usr/bin/tesseract"

# Application Settings (optional)
[app]
environment = "production"
log_level = "INFO"
max_upload_size_mb = 10
session_timeout_minutes = 60
name = "AGS AI Assistant"
base_url = ""

[smtp]
host = "smtp.gmail.com"
port = 587
username = ""
password = ""
from_email = ""
ssl = false

