[firebase]
api_key = "REPLACE"
auth_domain = "REPLACE.firebaseapp.com"
project_id = "REPLACE"
storage_bucket = "REPLACE.appspot.com"
messaging_sender_id = "REPLACE"
app_id = "REPLACE"

[app]
environment = "prod"

